package com.srmspro.ea;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import android.database.sqlite.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 DB db; LinearLayout root,content; TextView title; String user="Administrator";
 int blue=Color.rgb(21,101,192);
 public void onCreate(Bundle b){super.onCreate(b);db=new DB(this); showLogin();}
 TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(20,16,20,16);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);return b;}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);setContentView(root);}
 void showLogin(){base(); Space sp=new Space(this);root.addView(sp,new LinearLayout.LayoutParams(1,80)); TextView h=tv("EMERGENCY ALERT",28);h.setTextColor(blue);h.setGravity(17);root.addView(h);TextView sub=tv("Emergency Alert System",17);sub.setGravity(17);root.addView(sub);
  EditText u=new EditText(this);u.setHint("Username");u.setSingleLine();root.addView(u,new LinearLayout.LayoutParams(-1,60)); EditText p=new EditText(this);p.setHint("Password");p.setInputType(0x81);root.addView(p,new LinearLayout.LayoutParams(-1,60));
  Button login=btn("LOGIN");root.addView(login);login.setOnClickListener(v->{if(db.login(u.getText().toString().trim(),p.getText().toString()))showHome();else Toast.makeText(this,"Invalid username or password",Toast.LENGTH_SHORT).show();});
  root.addView(tv("Local Android edition • works offline",14));
 }
 void showHome(){base(); LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackgroundColor(blue);title=tv("Emergency Alert",21);title.setTextColor(Color.WHITE);bar.addView(title,new LinearLayout.LayoutParams(0,70,1));Button out=btn("LOGOUT");bar.addView(out);out.setOnClickListener(v->showLogin());root.addView(bar);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1)); nav(); dashboard();}
 void nav(){LinearLayout n=new LinearLayout(this);n.setPadding(4,4,4,4);String[] a={"Dashboard","Report","Notification","History"};for(String x:a){Button b=btn(x);n.addView(b,new LinearLayout.LayoutParams(0,55,1));b.setOnClickListener(v->{content.removeAllViews();if(x.equals("Dashboard"))dashboard();if(x.equals("Report"))report();if(x.equals("Notification"))notification();if(x.equals("History"))history();});}root.addView(n,1);}
 void heading(String s){TextView h=tv(s,25);h.setTextColor(blue);content.addView(h);}
 void dashboard(){heading("Dashboard");int total=db.count("fire",null), active=db.count("fire","status='Active'");content.addView(tv("Welcome, "+user,18));content.addView(tv("Emergency records: "+total+"\nActive alerts: "+active,19));Button add=btn("REPORT FIRE / EMERGENCY");content.addView(add);add.setOnClickListener(v->addFire());}
 void addFire(){final EditText area=new EditText(this);area.setHint("Area");final EditText room=new EditText(this);room.setHint("Room / Location");LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(30,10,30,10);l.addView(area);l.addView(room);new AlertDialog.Builder(this).setTitle("New Emergency Alert").setView(l).setPositiveButton("SAVE",(d,w)->{db.addFire(area.getText().toString(),room.getText().toString());Toast.makeText(this,"Emergency alert saved",Toast.LENGTH_SHORT).show();dashboard();}).setNegativeButton("CANCEL",null).show();}
 void report(){heading("Report");Button add=btn("+ New Alert");content.addView(add);add.setOnClickListener(v->addFire());Cursor c=db.rows();while(c.moveToNext()){final int id=c.getInt(0);String s="Area: "+c.getString(1)+"\nRoom: "+c.getString(2)+"\nStart: "+c.getString(3)+"\nStatus: "+c.getString(5);TextView r=tv(s,17);r.setBackgroundColor(0xffeeeeee);content.addView(r);Button done=btn(c.getString(5).equals("Active")?"Mark Resolved":"Resolved");content.addView(done);done.setEnabled(c.getString(5).equals("Active"));done.setOnClickListener(v->{db.resolve(id);report();});}c.close();}
 void notification(){heading("Notification");Cursor c=db.rows();int n=0;while(c.moveToNext()){if(c.getString(4).equals("Yes")){content.addView(tv("ALERT: Fire reported at "+c.getString(1)+" / "+c.getString(2),18));n++;}}c.close();if(n==0)content.addView(tv("No active notifications.",18));}
 void history(){heading("History");Cursor c=db.rows();while(c.moveToNext()){content.addView(tv(c.getString(3)+" • "+c.getString(1)+" / "+c.getString(2)+" • "+c.getString(5),16));}c.close();}
 static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"ea.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE user(u_id INTEGER PRIMARY KEY,fname TEXT,uname TEXT UNIQUE,pass TEXT,status TEXT)");d.execSQL("CREATE TABLE fire(f_id INTEGER PRIMARY KEY AUTOINCREMENT,area TEXT,room TEXT,stime TEXT,notify TEXT,status TEXT)");d.execSQL("INSERT INTO user VALUES(1,'Administrator','admin','admin','active')");}public void onUpgrade(SQLiteDatabase d,int a,int b){}boolean login(String u,String p){Cursor c=getReadableDatabase().rawQuery("SELECT u_id FROM user WHERE uname=? AND pass=? AND status='active'",new String[]{u,p});boolean ok=c.moveToFirst();c.close();return ok;}void addFire(String a,String r){ContentValues v=new ContentValues();v.put("area",a);v.put("room",r);v.put("stime",new SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.getDefault()).format(new Date()));v.put("notify","Yes");v.put("status","Active");getWritableDatabase().insert("fire",null,v);}Cursor rows(){return getReadableDatabase().rawQuery("SELECT f_id,area,room,stime,notify,status FROM fire ORDER BY f_id DESC",null);}int count(String t,String where){Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM "+t+(where==null?"":" WHERE "+where),null);c.moveToFirst();int n=c.getInt(0);c.close();return n;}void resolve(int id){ContentValues v=new ContentValues();v.put("status","Resolved");v.put("notify","No");getWritableDatabase().update("fire",v,"f_id=?",new String[]{String.valueOf(id)});}}
}
